// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bygvrbihkxgcbjcxrgar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5Z3ZyYmloa3hnY2JqY3hyZ2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTIwNTAsImV4cCI6MjA3MzI2ODA1MH0.W-FDMx3kR6m0lZnd_jhzsFI7NSeLwEIdTB8xTZCHEaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});